In [1]:
import numpy as np
# Membuat vector 
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [2]:
b = np.array([1.5, 2, 3.1, 4.9, 5.0])
print(b)

[1.5 2.  3.1 4.9 5. ]


In [3]:
# Membuat array multidimensi / matriks
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Membuat matriks dengan nilai nol
d = np.zeros([5,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
# Membuat matriks dengan nilai 1
e = np.ones([5,5])
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Membuat matriks identitas
f = np.identity(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# Perbedaan list di Python dan numpy array
x = [1,2,3,4,5]
y = [6,7,8,9,10]

xnp = np.array([1,2,3,4,5])
ynp = np.array([6,7,8,9,10])

# Penjumlahan list
hasil = x + y
print(hasil)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
# Penjumlahan array numpy
hasil2 = xnp + ynp
print(hasil2)

[ 7  9 11 13 15]


In [10]:
hasil3 = x - y
hasil4 = xnp - ynp
print(hasil3)
print(hasil4)

[-5 -5 -5 -5 -5]


In [ ]:
hasil5 = x*y
hasil6 = xnp*ynp
hasil7 = x/y
hasil8 = xnp/ynp

'''
TUGAS 1
JELASKAN PERBEDAAN HASIL DARI OPERASI ARITMATIKA ANTARA LIST DI PYTHON DAN ARRAY NUMPY
boleh tulis tangan atau diketik
'''

In [ ]:
'''
TUGAS 2
LAKUKAN OPERASI ARITMATIKA PADA MATRIKS,
APAKAH PERKALIAN PADA ARRAY SAMA DENGAN PERKALIAN PADA MATRIKS?
A + B
A - B
A * B
A / B
'''
A = np.array([[1,2,3], [0,-1,2]])
B = np.array([[4,5,6], [-1,1,1]])

In [12]:
# INDEXING, SLICING, ITERASI
a = np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [13]:
# Mengambil nilai
print('elemen ke 1 dari a adalah', a[0])
print('elemen ke 7 dari a adalah', a[6])
print('elemen terakhir dari a adalah', a[-1])

# Slicing
print('elemen dari 1-6 adalah', a[0:6])
print('elemen dari 4 sampai terakhir adalah', a[3:])
print('elemen dari awal sampai 5 adalah', a[:5])

# Iterasi
for i in a:
    print(i)

elemen ke 1 dari a adalah 0
elemen ke 7 dari a adalah 36
elemen terakhir dari a adalah 81
elemen dari 1-6 adalah [ 0  1  4  9 16 25]
elemen dari 4 sampai terakhir adalah [ 9 16 25 36 49 64 81]
elemen dari awal sampai 5 adalah [ 0  1  4  9 16]
0
1
4
9
16
25
36
49
64
81


In [15]:
# Perkalian matriks
k = np.array([[1,2,3], [4,3,5]])
j = np.array([[2,3], [1,1], [3,4]])
print(j)
print(k)

[[2 3]
 [1 1]
 [3 4]]
[[1 2 3]
 [4 3 5]]


In [16]:
A = np.dot(j,k)
print(A)

[[14 13 21]
 [ 5  5  8]
 [19 18 29]]


In [17]:
B = np.dot(k,j)
print(B)

[[13 17]
 [26 35]]


In [ ]:
'''
TUGAS 3
LAKUKAN PERKALIAN MATRIKS J DAN K SECARA MANUAL (SEPERTI SAAT ALJABAR LINEAR),
KEMUDIAN BANDINGKAN HASILNYA DENGAN PERHITUNGAN MENGGUNAKAN KOMPUTER.
'''

In [19]:
# Tranpose matriks
j.transpose()

array([[2, 1, 3],
       [3, 1, 4]])

In [25]:
# INVERS MATRIKS
a = np.array([[2,3], [1,1]])

# Invers dari a
a_inv = np.linalg.inv(a)

print(a)
print(a_inv)

[[2 3]
 [1 1]]
[[-1.  3.]
 [ 1. -2.]]


In [27]:
i = np.dot(a, a_inv)
print(i)
'''
TUGAS 4
JELASKAN KENAPA i MERUPAKAN MATRIKS IDENTITAS
'''

[[1. 0.]
 [0. 1.]]


In [28]:
# determinan
a = np.array([[2,3], [1,1]])
det_a = np.linalg.det(a)
print(det_a)

-1.0


In [ ]:
'''
TUGAS 5

x + y - z = 2
x - 2y + 3z = 13
-x - y + 5z = 6

Carilah penyelesaian dari sistem persamaan linear diatas dengan bantuan komputer (array numpy),
Carilah penyelesaian dari sistem persamaan linear diatas dengan perhitungan manual,
bandingkan hasil pekerjaan manual dengan hasil perhitungan komputer.
'''

Kumpulkan tugas melalui tautan https://forms.gle/ZZ12sSennbv6Noi77 sebelum perkuliahan minggu depan